package com.databasepreservation.common.server.batch.config;

import java.util.Map;

import org.springframework.batch.core.configuration.annotation.StepScope;
import org.springframework.batch.core.step.tasklet.Tasklet;
import org.springframework.batch.item.ExecutionContext;
import org.springframework.batch.item.ItemProcessor;
import org.springframework.batch.item.ItemReader;
import org.springframework.batch.item.ItemWriter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.databasepreservation.common.client.ViewerConstants;
import com.databasepreservation.common.server.batch.context.JobContext;
import com.databasepreservation.common.server.batch.context.JobContextRegistry;
import com.databasepreservation.common.server.batch.core.ChunkStepDefinition;
import com.databasepreservation.common.server.batch.core.TaskletStepDefinition;

/**
 * Configuration class that defines @StepScope proxies for Spring Batch
 * components. These proxies delegate execution to the actual StepDefinitions at
 * runtime, allowing late-binding of step context parameters.
 *
 * @author Gabriel Barros <gbarros@keep.pt>
 */
@Configuration
public class StepComponentsConfig {
  @Autowired
  private ApplicationContext applicationContext;

  @Autowired
  private JobContextRegistry contextRegistry;

  /**
   * Proxy for Chunk Readers. Works with any serializable type.
   */
  @Bean
  @StepScope
  public ItemReader<?> proxyReader(@Value("#{stepExecution.stepName}") String stepName,
    @Value("#{jobParameters['" + ViewerConstants.CONTROLLER_DATABASE_ID_PARAM + "']}") String databaseUUID,
    @Value("#{stepExecutionContext}") Map<String, Object> partitionCtx) {

    JobContext ctx = contextRegistry.get(databaseUUID);
    return getChunkDefinition(stepName).createReader(ctx, new ExecutionContext(partitionCtx));
  }

  /**
   * Proxy for Chunk Processors. Works with any serializable input/output types.
   */
  @Bean
  @StepScope
  public ItemProcessor<?, ?> proxyProcessor(@Value("#{stepExecution.stepName}") String stepName,
    @Value("#{jobParameters['" + ViewerConstants.CONTROLLER_DATABASE_ID_PARAM + "']}") String databaseUUID,
    @Value("#{stepExecutionContext}") Map<String, Object> partitionCtx) {

    JobContext ctx = contextRegistry.get(databaseUUID);
    return getChunkDefinition(stepName).createProcessor(ctx, new ExecutionContext(partitionCtx));
  }

  /**
   * Proxy for Chunk Writers.
   */
  @Bean
  @StepScope
  public ItemWriter<?> proxyWriter(@Value("#{stepExecution.stepName}") String stepName,
    @Value("#{jobParameters['" + ViewerConstants.CONTROLLER_DATABASE_ID_PARAM + "']}") String databaseUUID) {

    JobContext ctx = contextRegistry.get(databaseUUID);
    return getChunkDefinition(stepName).createWriter(ctx);
  }

  /**
   * Proxy for Tasklets. Delegates to TaskletStepDefinitions, which can represent
   * any arbitrary logic, including partitioned steps.
   */
  @Bean
  @StepScope
  public Tasklet proxyTasklet(@Value("#{stepExecution.stepName}") String stepName,
    @Value("#{jobParameters['" + ViewerConstants.CONTROLLER_DATABASE_ID_PARAM + "']}") String databaseUUID,
    @Value("#{stepExecutionContext}") Map<String, Object> partitionCtx) {

    JobContext ctx = contextRegistry.get(databaseUUID);
    return getTaskletDefinition(stepName).createTasklet(ctx, new ExecutionContext(partitionCtx));
  }

  // --- Helper Methods ---

  private ChunkStepDefinition<?, ?> getChunkDefinition(String stepName) {
    String beanName = extractBeanName(stepName);
    return applicationContext.getBean(beanName, ChunkStepDefinition.class);
  }

  private TaskletStepDefinition getTaskletDefinition(String stepName) {
    String beanName = extractBeanName(stepName);
    return applicationContext.getBean(beanName, TaskletStepDefinition.class);
  }

  /**
   * Removes suffixes like "Worker" or partition identifiers generated by Spring
   * Batch.
   */
  private String extractBeanName(String stepName) {
    return stepName.split(":")[0].replace("Worker", "");
  }
}
