name: Dispatch

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version to dispatch

jobs:
  dispatch:
    strategy:
      matrix:
        repo: [ 'keeps/dbptk-desktop' ]

    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: dispatch-main
          client-payload: '{"version": "${{ github.event.inputs.version }}", "flow": "main"}'
